version: '3.9'

services:
  # memcached:
  #   image: memcached:1.6.26
  #   container_name: memcached
  #   ports:
  #     - "11211:11211"
  #   command: memcached -m 64
  #   restart: unless-stopped

  redis:
    image: redis:7.2.4
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
